# Generated by Django 3.2.15 on 2022-10-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='Images/%Y/%m/%d/f024018c18da418ca8c92dba1115a7b8/', verbose_name='Imagen'),
        ),
    ]
