# Generated by Django 3.2.15 on 2022-10-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='Images/%Y/%m/%d/67141764eda44dff92a99094c870d06a/', verbose_name='Imagen'),
        ),
    ]
