# Generated by Django 3.2.15 on 2022-10-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='Images/%Y/%m/%d/d0af48a57fe7471e8423c66e2c824326/', verbose_name='Imagen'),
        ),
    ]
