# Generated by Django 3.2.15 on 2022-10-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='Images/%Y/%m/%d/fbb5441d0d6d49d68e1ce04e837719e2/', verbose_name='Imagen'),
        ),
    ]
