# Generated by Django 3.2.15 on 2022-10-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='Images/%Y/%m/%d/c1eb709730374ca4afebd4db23aaca59/', verbose_name='Imagen'),
        ),
    ]
