# Generated by Django 3.2.15 on 2022-10-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='Images/%Y/%m/%d/3e88e105df6d4b099e363dac87f18921/', verbose_name='Imagen'),
        ),
    ]
