# Generated by Django 3.2.15 on 2022-10-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='Images/%Y/%m/%d/ad8d2a805c394b4f93a5b8ce5742638a/', verbose_name='Imagen'),
        ),
    ]
