# Generated by Django 3.2.15 on 2022-10-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='Images/%Y/%m/%d/25cad667e36448a6aaf56a4a6b7bb92c/', verbose_name='Imagen'),
        ),
    ]
