# Generated by Django 3.2.15 on 2022-10-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='Images/%Y/%m/%d/974819531945480ba6d46f0a78304fbc/', verbose_name='Imagen'),
        ),
    ]
