# Generated by Django 3.2.15 on 2022-08-21 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Stock')),
                ('image', models.ImageField(max_length=50, upload_to='Images/%Y/%m/%d/', verbose_name='Imagen de Stock')),
                ('principal_file', models.FileField(upload_to='StockFiles/%Y/%m/%d/', verbose_name='Archivo del Stock')),
                ('first_backup_file', models.FileField(upload_to='StockFiles/%Y/%m/%d/', verbose_name='Primer archivo de respaldo')),
                ('second_backup_file', models.FileField(upload_to='StockFiles/%Y/%m/%d/', verbose_name='Segundo archivo de respaldo')),
                ('third_backup_file', models.FileField(upload_to='StockFiles/%Y/%m/%d/', verbose_name='Tercer archivo de respaldo')),
                ('name_column', models.CharField(max_length=50, verbose_name='Columna de nombre-producto')),
                ('price_column', models.CharField(max_length=50, verbose_name='Columna precio')),
                ('quantity_column', models.CharField(max_length=50, verbose_name='Columna cantidad')),
                ('category_column', models.CharField(default=None, max_length=50, verbose_name='Columna categorias')),
                ('added_date_column', models.CharField(default=None, max_length=50, verbose_name='Columna de fecha-añadido')),
                ('updated_date_column', models.CharField(default=None, max_length=50, verbose_name='Columna de fecha-renovado')),
                ('additional_column', models.CharField(default=None, max_length=50, verbose_name='Columna de fecha-renovado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Nuevos Stocks',
                'ordering': ['name'],
            },
        ),
    ]
