# Generated by Django 3.2.15 on 2022-08-14 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Stock')),
                ('stock_image', models.ImageField(max_length=50, unique=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Imagen de Stock')),
                ('stock_file', models.FileField(unique=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Archivo del Stock')),
                ('product_name_col', models.CharField(max_length=50, unique=True, verbose_name='Columna de nombre-producto')),
                ('price_col', models.DecimalField(decimal_places=2, max_digits=8, unique=True, verbose_name='Columna precio')),
                ('amount_col', models.IntegerField(unique=True, verbose_name='Columna cantidad')),
                ('categories_col', models.CharField(default=None, max_length=50, unique=True, verbose_name='Columna categorias')),
                ('added_date_col', models.CharField(default=None, max_length=50, unique=True, verbose_name='Columna de fecha-añadido')),
                ('renewal_date_col', models.CharField(default=None, max_length=50, unique=True, verbose_name='Columna de fecha-renovado')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Nuevo Stock',
                'verbose_name_plural': 'Nuevos Stocks',
                'ordering': ['stock_name'],
            },
        ),
    ]
