# Generated by Django 3.2.15 on 2022-08-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='added_date_column',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Columna de fecha-añadido'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='additional_column',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Columna de fecha-renovado'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='category_column',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Columna categorias'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='updated_date_column',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Columna de fecha-renovado'),
        ),
    ]
