# Generated by Django 3.2.15 on 2022-10-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20221028_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='products_generates',
        ),
        migrations.AlterField(
            model_name='stock',
            name='image',
            field=models.ImageField(upload_to='Images/%Y/%m/%d/f7a9ce30f23b4055894927861021aec1/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='principal_file',
            field=models.FileField(upload_to='StockFiles/%Y/%m/%d/261032079d534193bbff11da1263c111/', verbose_name='Archivo fuente'),
        ),
    ]
