# Generated by Django 3.2.15 on 2022-08-14 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.models import User



class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0002_auto_20220814_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='user',
            field=models.ForeignKey(default=User.objects.get(username="Carlos").pk, editable=False, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Usuario'),
            preserve_default=False,
        ),
    ]
