# Generated by Django 3.2.15 on 2022-08-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_stock_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_file',
            field=models.FileField(unique=True, upload_to='StockFiles/%Y/%m/%d/', verbose_name='Archivo del Stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_image',
            field=models.ImageField(max_length=50, unique=True, upload_to='Images/%Y/%m/%d/', verbose_name='Imagen de Stock'),
        ),
    ]
