# Generated by Django 3.2.15 on 2022-10-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20221030_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='image',
            field=models.ImageField(upload_to='Images/%Y/%m/%d/23a9876583764f36ac0261defa668c1b/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='principal_file',
            field=models.FileField(upload_to='StockFiles/%Y/%m/%d/ed2007847d9443c0a1aa75c17b0f09d4/', verbose_name='Archivo fuente'),
        ),
    ]
