# Generated by Django 3.2.15 on 2022-08-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20220821_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='first_backup_file',
            field=models.FileField(default='null', null=True, upload_to='StockFiles/%Y/%m/%d/', verbose_name='Primer archivo de respaldo'),
        ),
    ]
