# Generated by Django 3.2.15 on 2022-10-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20221030_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='image',
            field=models.ImageField(upload_to='Images/%Y/%m/%d/41deda9e08f049c788b2ce069e198b67/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='principal_file',
            field=models.FileField(upload_to='StockFiles/%Y/%m/%d/7fa3fdfe06ec4d2c81515e6f5c274b82/', verbose_name='Archivo fuente'),
        ),
    ]
