# Generated by Django 3.2.15 on 2022-10-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20221030_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='image',
            field=models.ImageField(upload_to='Images/%Y/%m/%d/b398f485f9444fdb9a0a8d1e4335e371/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='principal_file',
            field=models.FileField(upload_to='StockFiles/%Y/%m/%d/2355075ae3424ccfa2530ba697390470/', verbose_name='Archivo fuente'),
        ),
    ]
