# Generated by Django 3.2.15 on 2022-08-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20220821_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['name'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AlterField(
            model_name='stock',
            name='additional_column',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Nombres de columnas adicionales, separados por coma'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='image',
            field=models.ImageField(max_length=50, upload_to='Images/%Y/%m/%d/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='principal_file',
            field=models.FileField(upload_to='StockFiles/%Y/%m/%d/', verbose_name='Archivo fuente'),
        ),
    ]
