# Generated by Django 3.2.15 on 2022-08-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20220822_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='image',
            field=models.ImageField(upload_to='Images/%Y/%m/%d/', verbose_name='Imagen'),
        ),
    ]
