# Generated by Django 3.2.15 on 2022-10-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20221030_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='image',
            field=models.ImageField(upload_to='Images/%Y/%m/%d/4b30a3cbbf904a81a6930e55a98d909a/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='principal_file',
            field=models.FileField(upload_to='StockFiles/%Y/%m/%d/c74b646b97684b1687fc3eb3eeecdb5e/', verbose_name='Archivo fuente'),
        ),
    ]
