# Generated by Django 3.2.15 on 2022-10-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20221030_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='image',
            field=models.ImageField(upload_to='Images/%Y/%m/%d/e67ce08b2af14fe89f68cd2c3a0a6abd/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='principal_file',
            field=models.FileField(upload_to='StockFiles/%Y/%m/%d/b55fb061ca344398988180a71713e72c/', verbose_name='Archivo fuente'),
        ),
    ]
