# Generated by Django 3.2.15 on 2022-10-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20221030_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='image',
            field=models.ImageField(upload_to='Images/%Y/%m/%d/c9fd21d9fd1448bab6c35bce8cf7ccf8/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='principal_file',
            field=models.FileField(upload_to='StockFiles/%Y/%m/%d/dffd134a11554939a423503f03a0b255/', verbose_name='Archivo fuente'),
        ),
    ]
