# Generated by Django 3.2.15 on 2022-10-28 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/23c0355b65baa45f0b5dcce3c6a14e418/', verbose_name='Archivo auxiliar de respaldo')),
                ('first', models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/026fc54e5e8c4be1952f3871b45d25c0/', verbose_name='Primer archivo de respaldo')),
                ('second', models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/fd35739d4cc04f279e5ac58f2f3f7439/', verbose_name='Segundo archivo de respaldo')),
                ('third', models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/f448b40f611c4b688f9cfd022c6b2445/', verbose_name='Tercer archivo de respaldo')),
                ('cuarto', models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/5bdb686ea8584b9e90f81b6167c26a35/', verbose_name='Tercer archivo de respaldo')),
                ('stock', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.stock', verbose_name='Stocks')),
            ],
            options={
                'verbose_name': 'Respaldo',
                'verbose_name_plural': 'Respaldos',
            },
        ),
    ]
