# Generated by Django 3.2.15 on 2022-10-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='cuarto',
        ),
        migrations.AlterField(
            model_name='backup',
            name='first',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/4a2afc7290424e0287248f19a65623ea/', verbose_name='Primer archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='hidden',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/25b4ac5aca6b248e5b0effa418064afce/', verbose_name='Archivo auxiliar de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='second',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/0aeee46672dc4b70b5bd277fa3f1a673/', verbose_name='Segundo archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='third',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/b87b887526364fa9934f9877dae30f4f/', verbose_name='Tercer archivo de respaldo'),
        ),
    ]
