# Generated by Django 3.2.15 on 2022-10-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_auto_20221028_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='first',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/8e792af55f624e1b8fc441eeb15d99b6/', verbose_name='Primer archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='hidden',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/6571541da8424314a3ba4a95e8f08dee/', verbose_name='Archivo auxiliar de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='second',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/2a0eeb93b86b45a7965f24f1523b4bc3/', verbose_name='Segundo archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='third',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/cdea622bad234375bcf78ddd6c1fea7a/', verbose_name='Tercer archivo de respaldo'),
        ),
    ]
