# Generated by Django 3.2.15 on 2022-10-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0004_auto_20221028_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='hidden',
        ),
        migrations.AddField(
            model_name='backup',
            name='current',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/bfc5b2d5c98b40c38980fd5fa866d48b/', verbose_name='Archivo auxiliar de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='first',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/5c641a1eab144a8fbf039db5dd3ccd56/', verbose_name='Primer archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='second',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/cb310f52b7b24f6d973e8c108ffe3763/', verbose_name='Segundo archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='third',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/30dd2bc09bdc45b9b40451655b1eb410/', verbose_name='Tercer archivo de respaldo'),
        ),
    ]
