# Generated by Django 3.2.15 on 2022-10-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0006_auto_20221029_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='current',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/6c78b69dc459498b9aec902e0a7b324e/', verbose_name='Archivo auxiliar de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='first',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/ff7c0d739d454897b4947fb103b2ace6/', verbose_name='Primer archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='second',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/9f0b0bb501fa4ae99b75b9c1d3a4a2f6/', verbose_name='Segundo archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='third',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/8260850ce9b34acd80ab4746a605ebcc/', verbose_name='Tercer archivo de respaldo'),
        ),
    ]
