# Generated by Django 3.2.15 on 2022-10-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0007_auto_20221030_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='current',
            field=models.FileField(null=True, upload_to='BackupFiles/%Y/%m/%d/0373d53e21d84a0cad84c28f1a639a9b/', verbose_name='Archivo auxiliar de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='first',
            field=models.FileField(null=True, upload_to='BackupFiles/%Y/%m/%d/4baa797141e04ce1bb5664d8d6511f14/', verbose_name='Primer archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='second',
            field=models.FileField(null=True, upload_to='BackupFiles/%Y/%m/%d/84e688f7c9ed49b88eddc73060899aee/', verbose_name='Segundo archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='third',
            field=models.FileField(null=True, upload_to='BackupFiles/%Y/%m/%d/929bd8c31b194d93b3250427d37b673b/', verbose_name='Tercer archivo de respaldo'),
        ),
    ]
