# Generated by Django 3.2.15 on 2022-10-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0008_auto_20221030_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='current',
            field=models.FileField(default=None, null=True, upload_to='BackupFiles/%Y/%m/%d/97179d6a3a4244eba39b58736f231333/', verbose_name='Archivo auxiliar de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='first',
            field=models.FileField(default=None, null=True, upload_to='BackupFiles/%Y/%m/%d/51948fb116e940798c81f6d1a02b8914/', verbose_name='Primer archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='second',
            field=models.FileField(default=None, null=True, upload_to='BackupFiles/%Y/%m/%d/131fb6ba17394a7b9ad000dc4e4108a6/', verbose_name='Segundo archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='third',
            field=models.FileField(default=None, null=True, upload_to='BackupFiles/%Y/%m/%d/0a874f75e7b1489fab7d05457005f6ac/', verbose_name='Tercer archivo de respaldo'),
        ),
    ]
