# Generated by Django 3.2.15 on 2022-10-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0009_auto_20221030_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='first_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de primer respaldo'),
        ),
        migrations.AddField(
            model_name='backup',
            name='second_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de segundo respaldo'),
        ),
        migrations.AddField(
            model_name='backup',
            name='third_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de tercer respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='current',
            field=models.FileField(default=None, null=True, upload_to='BackupFiles/%Y/%m/%d/5cf0eecbc9fc4d618a3068393e2b9ff3/', verbose_name='Archivo auxiliar de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='first',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/0c8230d6fa0f427096b018377555af78/', verbose_name='Primer archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='second',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/1288831058d442dd991a8ca8af21360f/', verbose_name='Segundo archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='third',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/691e62134735456b92107a59fee7764e/', verbose_name='Tercer archivo de respaldo'),
        ),
    ]
