# Generated by Django 3.2.15 on 2022-10-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0010_auto_20221030_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='current',
            field=models.FileField(default=None, null=True, upload_to='BackupFiles/%Y/%m/%d/cbb5ef32202b42b19728bf498ff63d69/', verbose_name='Archivo auxiliar de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='first',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/a989009e291f4d249b7a2061e2a74c9b/', verbose_name='Primer archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='first_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de primer respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='second',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/a855622c4af0471a959579b66a4ad998/', verbose_name='Segundo archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='second_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de segundo respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='third',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/dd715bf39eae4103b8368db39bc62130/', verbose_name='Tercer archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='third_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de tercer respaldo'),
        ),
    ]
