# Generated by Django 3.2.15 on 2022-10-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0011_auto_20221030_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='current',
            field=models.FileField(default=None, null=True, upload_to='BackupFiles/%Y/%m/%d/dd2ee9485c2d4e0999d2b92dae165f46/', verbose_name='Archivo auxiliar de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='first',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/6cf316ddc6c14398a9bab1783f8edc8b/', verbose_name='Primer archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='first_date',
            field=models.DateTimeField(default='NULL', verbose_name='Fecha de primer respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='second',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/6c14f1d6dc4048f6a06ab6d58c39a6f6/', verbose_name='Segundo archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='second_date',
            field=models.DateTimeField(default='NULL', verbose_name='Fecha de segundo respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='third',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/6967f656aa6c4793a1d5df8bedbee87c/', verbose_name='Tercer archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='third_date',
            field=models.DateTimeField(default='NULL', verbose_name='Fecha de tercer respaldo'),
        ),
    ]
