# Generated by Django 3.2.15 on 2022-10-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0012_auto_20221030_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='current',
            field=models.FileField(default=None, null=True, upload_to='BackupFiles/%Y/%m/%d/88bae9feaa104af1bf5206ab5000859a/', verbose_name='Archivo auxiliar de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='first',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/4b75a896c72b4df9b6c0172e5921c741/', verbose_name='Primer archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='second',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/c7c73b8f4bb44c2aad992cfc2d2f10c4/', verbose_name='Segundo archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='third',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/429a89efb492400482b659746e3c0f55/', verbose_name='Tercer archivo de respaldo'),
        ),
    ]
