# Generated by Django 3.2.15 on 2022-10-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0013_auto_20221030_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='current',
            field=models.FileField(default=None, null=True, upload_to='BackupFiles/%Y/%m/%d/751a7bae94904ea7acda78b2511499db/', verbose_name='Archivo auxiliar de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='first',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/3da1c19eeaa445f5b33746e2d182a19d/', verbose_name='Primer archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='first_date',
            field=models.DateTimeField(default=None, verbose_name='Fecha de primer respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='second',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/79b90c6bef5b42e691ef2c3a2df28461/', verbose_name='Segundo archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='second_date',
            field=models.DateTimeField(default=None, verbose_name='Fecha de segundo respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='third',
            field=models.FileField(default='NULL', null=True, upload_to='BackupFiles/%Y/%m/%d/137edef5b1004791aa4e691dd360a902/', verbose_name='Tercer archivo de respaldo'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='third_date',
            field=models.DateTimeField(default=None, verbose_name='Fecha de tercer respaldo'),
        ),
    ]
